# AeroSpace configuration
# Customized for Lyra with Alt as primary modifier

after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical =   8
    outer.left =       8
    outer.bottom =     8
    outer.top =        8
    outer.right =      8

[mode.main.binding]
    # Layout commands (Alt + / or ,)
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # Focus commands (Alt + H/J/K/L) - Vi keys
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # Move commands (Alt+Shift + H/J/K/L)
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # Resize commands (Alt + - or =)
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # Workspace navigation (Alt + 1-9)
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # Move window to workspace (Alt+Shift + 1-9)
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    # Workspace back and forth (Alt + Tab)
    alt-tab = 'workspace-back-and-forth'

    # Maximize window (Alt + F)
    alt-f = 'fullscreen'

    # Join with adjacent windows (Ctrl + H/J/K/L)
    ctrl-h = 'join-with left'
    ctrl-j = 'join-with down'
    ctrl-k = 'join-with up'
    ctrl-l = 'join-with right'

    # Service mode (Alt + ;)
    alt-semicolon = 'mode service'

# Service mode for additional commands
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']
    backspace = ['close-all-windows-but-current', 'mode main']

    # Join with other windows (Alt + H/J/K/L in service mode)
    alt-h = ['join-with left', 'mode main']
    alt-j = ['join-with down', 'mode main']
    alt-k = ['join-with up', 'mode main']
    alt-l = ['join-with right', 'mode main']
